markdown: kramdown
url: https://nourj9.github.io
title: Nouraldin Jaber
author: Nouraldin Jaber
description: Graduate Research Assistant at Purdue University
avatar: photo.jpg
email: njaber@purdue.edu
github: nourj9 
twitter: NouraldinJaber
linkedin: nouraldin-jaber-b601b1a7 
permalink: /blog/:year/:month/:day/:title

# needed for travis-ci build
exclude: [vendor]
